title: Md Tawhid Chowdhury
logo: /assets/img/headshot_circle.png
description: With a passion for software development especially with agile practices, over 7 years of software development experience spanning .NetCore, ASP.NET development. Also experience of working with Angular, AngualJS, React, JQeury, BootStrap CSS for client side development; MSSQL, PostgreSQL, SQLite, Mongo, Apache Solr, Elasticseach and Git, SVN for version controlling.
show_downloads: false
theme: jekyll-theme-minimal
